---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

workspace:
  base: /usr/local/java/apps
  path: mongo_test

steps:
  - name: build
    image: gradle:6.6.1-jdk11
    environment:
    commands:
      - ./gradlew

  - name: test
    image: gradle:6.6.1-jdk11
    environment:
      TZ: 'Asia/Tokyo'
    commands:
      - ./gradlew


services:
  - name: mongors001
    image: mongo:3.4.5
    command: mongod --replSet rs1 --noprealloc --smallfiles
    ports:
      - 27017
  - name: mongors002
    image: mongo:3.4.5
    command: mongod --replSet rs1 --noprealloc --smallfiles
    ports:
      - 27017
  - name: mongors003
    image: mongo:3.4.5
    command: mongod --replSet rs1 --noprealloc --smallfiles
    ports:
      - 27017
